apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mediawiki-deployment
  labels:
    app: mediawiki
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mediawiki
        type: web
    spec:
      containers:
        - name: mediawiki
          image: ajitabh7/mediawiki7777777:v1
          ports:
            - containerPort: 80
              name: httpd-port
          env:
            - name: MEDIAWIKI_DB_HOST
              value: mariadb-service
            - name: MEDIAWIKI_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbuser
            - name: MEDIAWIKI_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbpassword
            - name: MEDIAWIKI_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbname  
